### ISSUE TITLE
Question about folder quota

### ISSUE THREAD

**Issue by ArnoLP** [keensoft/alfresco-myfiles-quota#10]
Hello,

I am currently testing the addon, and it works really fine for my first tests. Thanks for providing it.

However, I've got 1 question :

How can I get the quota and the current used size for a specific folder, which is not the user Home folder ?

Is it possible to apply the same kind of request mechanism as for the user Home folder ?
(curl -v -u admin:admin "http://localhost:8080/alfresco/service/keensoft/myfiles/quota/{username}")

Would it be possible to get the current defined quota when we click on the "Folder Quotas" action of a folder, instead of an empty box, if the folder already gets a quota ?

Or would there be another mean ?

Thanks in advance for your help.

Kind Regards,

Arnaud.

**Comment by angelborroy** [comment]
If you click at `Edit properties` on any folder marked for quota, you can access to `Quota` and `Usage` customized properties. 

You can also use standard Alfresco REST API and CMIS API to recover node metadata by using curl.

**Comment by ArnoLP** [comment]
Thanks for your feedback. I should have seen this ...
