### ISSUE TITLE
The quota doesn't work on alfresco 5.2

### ISSUE THREAD

**Issue by githublivier** [keensoft/alfresco-myfiles-quota#11]
Hi,

I've installed the addon on a v5.2 alfresco community.
When I create a new user, his home user's quota is set to the value that I add in the alfresco-global-properties file
However, I can add pictures whitout limits

When I execute :

curl -v -u admin:admin "http://localhost:8080/alfresco/service/keensoft/myfiles/quota/{quota}"

I get :

{"quota":104857600,"currentSize":21256673} --> the quota of my home user's folder is set to 10Mb but I  have been able to add for more than 20Mb 

Thanks

**Comment by angelborroy-ks** [comment]
I've installed and tested in 201707 successfully

According to your data:

104857600 = 100 MB
21256673 = 21 MB

You still have space available in that folder.

**Comment by githublivier** [comment]
My mistake
Sorry and thank you
