### ISSUE TITLE
Al aplicar una quota mediante webscripts sale un error

### ISSUE THREAD

**Issue by 4lfr3d7115** [keensoft/alfresco-myfiles-quota#3]
Centos 6.6
Alfresco comunnity 5.0.d

Este es el webscript y el error:
curl -v -u admin -X POST -d '{"quota":"104857600"}'  "http://172.16.60.115:8080/alfresco/service/keensoft/myfiles/quota/user.name"

Enter host password for user 'admin':
* About to connect() to 172.16.60.115 port 8080 (#0)
*   Trying 172.16.60.115... connected
* Connected to 172.16.60.115 (172.16.60.115) port 8080 (#0)
* Server auth using Basic with user 'admin'
> POST /alfresco/service/keensoft/myfiles/quota/user.name HTTP/1.1
> Authorization: Basic YWRtaW46QWJhY3VzMDE=
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 172.16.60.115:8080
> Accept: */*
> Content-Length: 21
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 500 Internal Server Error
< Server: Apache-Coyote/1.1
< Cache-Control: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Pragma: no-cache
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Mon, 20 Apr 2015 15:03:08 GMT
< Connection: close
<
{
    "status" :
  {
    "code" : 500,
    "name" : "Internal Error",
    "description" : "An error inside the HTTP server which prevented it from fulfilling the request."
  },

  "message" : "Unexpected token END OF FILE at position 0.",
  "exception" : "java.io.IOException - Unexpected token END OF FILE at position 0.",

  "callstack" :
  [
          ""      ,"Unexpected token END OF FILE at position 0."
      ,"org.json.simple.parser.JSONParser.parse(JSONParser.java:257)"
      ,"org.json.simple.parser.JSONParser.parse(JSONParser.java:81)"
      ,"org.json.simple.parser.JSONParser.parse(JSONParser.java:75)"
      ,"es.keensoft.alfresco.action.webscript.MyFilesQuotaPost.execute(MyFilesQuotaPost.java:42)"
      ,"org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:437)"
      ,"org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:619)"
      ,"org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:399)"
      ,"org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:280)"
      ,"org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)"
      ,"org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)"
      ,"org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)"
      ,"javax.servlet.http.HttpServlet.service(HttpServlet.java:727)"
      ,"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)"
      ,"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)"
      ,"org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
      ,"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)"
      ,"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)"
      ,"org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)"
      ,"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)"
      ,"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)"
      ,"org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)"
      ,"org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)"
      ,"org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)"
      ,"org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)"
      ,"org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)"
      ,"org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)"
      ,"org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)"
      ,"org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)"
      ,"org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)"
      ,"org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)"
      ,"org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2403)"
      ,"java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)"
      ,"java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)"
      ,"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
      ,"java.lang.Thread.run(Thread.java:745)"
      ,"java.io.IOException: Unexpected token END OF FILE at position 0."
      ,"es.keensoft.alfresco.action.webscript.MyFilesQuotaPost.execute(MyFilesQuotaPost.java:63)"

  ],

  "server" : "Community v5.0.0 (d r99759-b2) schema 8,022",
  "time" : "Apr 20, 2015 10:03:08 AM"
}

* Closing connection #0

**Comment by angelborroy** [comment]
"user.name" hace referencia al nombre de usuario en Alfresco. Sustituye en tu invocación curl "user.name" por el nombre de usuario, por ejemplo, admin.

curl -v -u admin -X POST -d '{"quota":"104857600"}' "http://172.16.60.115:8080/alfresco/service/keensoft/myfiles/quota/admin"

**Comment by 4lfr3d7115** [comment]
Efectivamente "user.name" lo utilize como ejemplo  para que no se presente el nombre de los usuarios del sistema.  En realidad la invocacion se hace sobre un nombre real de usuario existente en el sistema y provoca este error.

**Comment by angelborroy** [comment]
Por favor, prueba a realizar la invocación de la siguiente manera:

curl -u admin:admin -H 'Content-Type: application/json' -d '{"quota":"104857600"}' "http://localhost:9080/alfresco/service/keensoft/myfiles/quota/user.name"

Si verificas su funcionamiento, actualizaremos la documentación.

Gracias

**Comment by 4lfr3d7115** [comment]
Funciono perfectamente Angel. adjunto invocación. Gracias.
curl -v -u admin:admin -H 'Content-Type: application/json' -d '{"quota":"104857600"}'  "http://localhost:8080/alfresco/service/keensoft/myfiles/quota/user.name"
