### ISSUE TITLE
Quota not checked on move or restore of document

### ISSUE THREAD

**Issue by michaelmrotzek** [keensoft/alfresco-myfiles-quota#6]
Alfresco 5.0.d CE
alfresco-myfiles-quota Addon Release 2.0.0 (https://github.com/keensoft/alfresco-myfiles-quota/releases/tag/2.0.0)

1. **restore from trash can**
create a folder 
set quota to 5 MB
upload content so that usage is about 4.75MB
delete file 2MB
upload another file approx. 2 MB
restore deleted file from user-trashcan
=> folder quota not checked, the content has been restored and the folder contains more than 5MB

2. **move file to folder**
create a folder 
set quota to 5 MB
upload content so that usage is about 4.75MB
move 4MB file from another folder into the quota folder
=> folder quota not checked, the content has been moved and the folder contains more than 5MB

**Comment by angelborroy-ks** [comment]
Thanks for your comments and testing services.

New version has been released at https://github.com/keensoft/alfresco-myfiles-quota/releases/tag/2.0.1 including your requests.

**Comment by michaelmrotzek** [comment]
Thanks for your quick fix. Works for me!
