### ISSUE TITLE
Folder size calculation not working (nodes without content)

### ISSUE THREAD

**Issue by michaelmrotzek** [keensoft/alfresco-myfiles-quota#7]
hey, 
we´re using https://github.com/atolcd/alfresco-event-scheduling addon. This will create nodes in a site without content (see screnshot).

![image](https://cloud.githubusercontent.com/assets/2362114/11745685/3d8412da-a01a-11e5-88a9-1d0fe5e94ebe.png)

When trying to set a folder quota on such a site containing at least one event node an NPE raises:
```Caused by: java.lang.NullPointerException
	at org.alfresco.extension.folderquota.FolderUsageCalculator.calculateFolderSize(FolderUsageCalculator.java:64)
	at org.alfresco.extension.folderquota.FolderUsageCalculator.calculateFolderSize(FolderUsageCalculator.java:59)
	at org.alfresco.extension.folderquota.FolderUsageCalculator.calculateFolderSize(FolderUsageCalculator.java:59)
	at org.alfresco.extension.folderquota.FolderUsageCalculator.calculateFolderSize(FolderUsageCalculator.java:59)```

Solution seems pretty simple. (FolderUsageCalculator.java:64)
```
QName nodeType = nodeService.getType(fi.getNodeRef());
if(nodeType.isMatch(ContentModel.TYPE_FOLDER))
{
	size = size + calculateFolderSize(fi.getNodeRef());
}
else
{
	ContentData contentRef = (ContentData) nodeService.getProperty(fi.getNodeRef(), ContentModel.PROP_CONTENT);
	if(conteRef != null) {
		size = size + contentRef.getSize();
	}
}
```

**Comment by angelborroy-ks** [comment]
Thanks again for spending your time on these feedbacks. Please, feel free to provide us pull request in the future.

We've included your modification and it's available at https://github.com/keensoft/alfresco-myfiles-quota/releases/tag/2.0.2

**Comment by michaelmrotzek** [comment]
Yes, of course. But I didn´t get it fast working in eclipse ide ;) 
Thanks!
